### ISSUE TITLE
Implement init model

### ISSUE THREAD

**Issue by karolmie1** [karolmie1/PSO_Algorithm_Implementation#2]
+#Model structure:
+#list of:
+# - best point globally known
+#     - coordinates
+#     - quality
+# - list of points
+#     - vector of best known coordinates for point
+#     - vector of current coordinates
+#     - vector of velocity
+#     - quality

**Comment by mklecha** [comment]
Hey, dude, new idea. How about we refactor our model so that it contains information about both velocity and coords in one list? I guess it would be better to have entire information about a particle in one place. What do you think?

**Comment by karolmie1** [comment]
If you want to then go ahead, create new issue "model refactoring" for example, and start to work. Remember to fix all tests. Be warned that this new model will make few functions much more complex.

It is good idea if we didn't have to follow this metaheuristic pattern

But maybe it will be better. Show me working pull request, and we will decide.
