### ISSUE TITLE
Implement model update

### ISSUE THREAD

**Issue by karolmie1** [karolmie1/PSO_Algorithm_Implementation#4]
#TODO: implement and test - substitute current coordinates
+   #                         - count new velocities
+   #                         - update global best
+   #                         - update local best

**Comment by karolmie1** [comment]
Mind that updating particles coordinates takes place in variation, here only global best + new velocities.

**Comment by mklecha** [comment]
OK, I got it.

**Comment by mklecha** [comment]
I changed the description - I think that updating local best should also be made in this point

**Comment by mklecha** [comment]
Close after reviews
